export const SAVE_COMPANIES = "SAVE_COMPANIES";
export const SAVE_COMPANY_DETAIL = "SAVE_COMPANY_DETAIL";
export const SAVE_COMPANY_TYPES = "SAVE_COMPANY_TYPES";
export const CLEAN_COMPANIES = "CLEAN_COMPANIES";
